const translations = {
  ru: {
    "nav.about": "О предприятии",
    "nav.geography": "География добычи",
    "nav.products": "Продукция",
    "section.advantagesTitle": "Технологические преимущества",
    "adv.card1Title": "Мойка щебня",
    "adv.card1Text": "Удаление пыли и мелких частиц для повышения качества бетона и асфальта.",
    "adv.card2Title": "Современное оборудование",
    "adv.card2Text": "Дробильно-сортировочные установки Sandvik и HYDROCONE.",
    "adv.card3Title": "Контроль качества",
    "adv.card3Text": "Многоступенчатая проверка каждой партии, международная сертификация.",
    "adv.card4Title": "Надёжность",
    "adv.card4Text": "Более 65 лет на рынке, стабильное качество, доверие крупнейших заказчиков.",
    "section.resourcesTitle": "Месторождения",
    "section.galleryTitle": "Галерея",
    "resources.header.name": "Название",
    "resources.header.volume": "Объем",
    "resources.header.product": "Продукция",
    "resources.row1.name": "Котур-Булакское",
    "resources.row1.volume": "10 млн м³",
    "resources.row1.product": "щебень, порфириты",
    "resources.row2.name": "Капчагайское-2",
    "resources.row2.volume": "8 млн м³",
    "gallery.img1.alt": "Производственный цех",
    "gallery.img2.alt": "Оборудование на стройке",
    "gallery.img3.alt": "Щебень",
    "gallery.img4.alt": "Строительная техника",
    "gallery.img5.alt": "Производственный цех 2",
    "resources.row2.product": "строительный песок",
    "resources.row3.name": "Первомайское-2 Южное",
    "resources.row3.volume": "4 млн м³",
    "resources.row3.product": "мытый песок",
    "section.geographyTitle": "География добычи",
    "nav.projects": "Достижения и Ключевые проекты",
    "nav.contacts": "Контакты",
    "home.title": "Производитель щебня, песка и строительных материалов",
    "home.subtitle": "Основано в 1957 году. Мощности переработки бутового камня — до 1 000 000 тонн в год.",
    "home.cta": "Связаться с нами",
    "home.card1Title": "Качество",
    "home.card1Text": "Контроль качества и сертификация продукции по ГОСТ и международным стандартам.",
    "home.card2Title": "Поставки",
    "home.card2Text": "Обеспечиваем строительные объекты по всему Казахстану.",
    "section.aboutTitle": "О предприятии",
    "section.aboutText": "ТОО «АКНМ ТК» — одно из старейших предприятий строительной отрасли Казахстана. Основано в 1957 году как Алма-Атинский комбинат нерудных материалов (АКНМ). Сегодня предприятие специализируется на добыче, переработке и поставке щебня, песка, песчано-гравийных смесей и бетонных изделий.",
    "section.capacityTitle": "Мощности",
    "section.capacityText": "Годовая мощность переработки бутового камня — до <b>1 000 000 тонн</b>. Производственная база — более 15 гектаров. Современные дробильно-сортировочные линии Sandvik и HYDROCONE.",
    "section.qualityTitle": "Контроль качества",
    "section.qualityText": "Продукция сертифицирована и проходит регулярную лабораторную проверку. Контроль подтверждён британской лабораторией «SANDBERG» (Лондон).",
    "section.marketTitle": "Анализ рынка",
    "section.marketOverviewTitle": "Обзор рынка",
    "section.marketOverviewText": "Доля ТОО «АКНМ ТК» в Алматы и Алматинской области более 40%",
    "section.marketCompetitionTitle": "Конкурентная среда",
    "section.marketCompetitionText1": "Ключевое конкурентное преимущество: Уникальность породы парфирит М–1200+",
    "section.marketCompetitionText2": "По шкале Протодьяконова — 2 категория, коэффициент крепости 15. Технология переработки камня и широкий ассортимент продукции.",
    "section.marketTrendsTitle": "Тенденции и возможности",
    "section.marketTrendsText": "Растущий спрос на экологически чистые и прочные строительные материалы.<br>Возможности для экспорта продукции в страны Центральной Азии.",
    "section.geographyIntro": "ТОО «АКНМ ТК» разрабатывает карьеры и производит высококачественную продукцию в основном регионе Казахстана с суммарными запасами:",
    "section.geoReserve1": "«Котур Булакское» — 10 млн. м³",
    "section.geoReserve2": "«Капчагайское 2» — 8 млн. м³",
    "section.geoReserve3": "«Первомайское 2 Южный» — 4 млн. м³",
    "section.geographyConclusion": "Эти запасы позволяют ТОО «АКНМ ТК» быть ведущим поставщиком строительных материалов в регионе, поддерживая крупные строительные проекты и инфраструктуру Казахстана.",
    "section.projectsTitle": "Достижения и ключевые проекты",
    "section.projectsText": "ТОО «АКНМ ТК» активно участвует в реализации крупных строительных и инфраструктурных проектов по всему Казахстану, подтверждая свою репутацию как надежного поставщика высококачественных строительных материалов, отмеченного почетными наградами и сертификатами.",
    "project1": "Дворец Республики",
    "project2": "Каток «Медео»",
    "project3": "Гостиница «Казахстан»",
    "project4": "Гостиница «Анкара»",
    "project5": "Аэропорт Алматы",
    "project6": "Космодром «Байконур»",
    "project7": "Метрополитен Алматы",
    "project8": "Казахстан Темир Жолы",
    "project9": "Фарфоровые заводы",
    "project10": "ТрансСтройМост",
    "section.resourcesTitle": "Месторождения",
    "section.galleryTitle": "Галерея",
    "project11": "КазАвтоДор",
    "section.productsTitle": "Продукция",
    "section.productsText": "Продукция ТОО «АКНМ ТК» находит широкое применение в строительстве, дорожном хозяйстве, железнодорожном строительстве и других отраслях, благодаря высокому качеству, экологической безопасности и соответствию современным стандартам.",
    "productTable.header": "Наименование продукции",
    "productTable.item1": "Щебень из плотных горных пород для строительных работ — ГОСТ 8267-93",
    "productTable.item2": "Щебень из плотных горных пород для балластного слоя железнодорожного пути — ГОСТ 7392-2002",
    "productTable.item3": "Смеси щебёночно-песчаные — ГОСТ 25607-94",
    "productTable.item4": "Песок для строительных работ — ГОСТ 8736-93",
    "productTable.item5": "Известняковый или доломитовый щебень — ГОСТ 8267-93",
    "productCard.1": "Щебень фракции 5x20 (мытый)",
    "productCard.2": "Щебень фракции 5x20 (сухой)",
    "productCard.3": "Щебень фракции 20x40",
    "productCard.4": "Щебень фракции 25x60",
    "productCard.5": "Щебень фракции 40x70",
    "productCard.6": "Щебень фракции 70x150",
    "productCard.7": "Песок дроблёный (мытый)",
    "productCard.8": "Песок дроблёный (сухой)",
    "productCard.9": "Песок мытый",
    "productCard.10": "Песок природный",
    "productCard.11": "ПЩС (С2-0x20)",
    "productCard.12": "ПЩС (С4-0x70)",
    "productCard.13": "ПЩС (С1-0x40)",
    "productCard.14": "Отходы",
    "section.contactsTitle": "Контакты",
    "section.contactsTitle": "Контакты",
    "contacts.addressLabel": "Адрес:",
    "contacts.address": "РК, Алматинская обл., Талгарский р-н, с. Бесагаш, ул. Чехова 9г",
    "contacts.phoneLabel": "Телефоны:",
    "contacts.phone1": "+7 (727) 387‒40‒02",
    "contacts.phone2": "+7‒775‒734‒12‒13",
    "contacts.emailLabel": "Email:",
    "contacts.email": "aknm-tk@bk.ru",
    "contacts.name": "Имя",
    "contacts.phone": "Телефон",
    "contacts.emailInput": "Email",
    "contacts.message": "Сообщение",
    "contacts.sendButton": "Отправить",
    "contacts.whatsappButton": "Написать в WhatsApp"  
  },

  kk: {
    
    "nav.about": "Кәсіпорын туралы",
    "nav.geography": "Өндіру географиясы",
    "nav.products": "Өнімдер",
    "section.resourcesTitle": "Кен орындары",
    "section.galleryTitle": "Галерея",
    "section.geographyTitle": "Өндіру географиясы",
    "nav.projects": "Жетістіктер мен жобалар",
    "nav.contacts": "Байланыстар",
    "section.resourcesTitle": "Кен орындары",
    "section.advantagesTitle": "Технологиялық артықшылықтар",
    "adv.card1Title": "Қиыршық тасты жуу",
    "resources.header.name": "Атауы",
    "resources.header.volume": "Көлемі",
    "resources.header.product": "Өнім",
    "resources.row1.name": "Котур-Булакское",
    "resources.row1.volume": "10 млн м³",
    "resources.row1.product": "қиыршық тас, порфирит",
    "resources.row2.name": "Капчагайское-2",
    "gallery.img1.alt": "Өндірістік цех",
    "gallery.img2.alt": "Құрылыс жабдықтары",
    "gallery.img3.alt": "Қиыршық тас",
    "gallery.img4.alt": "Құрылыс техникасы",
    "gallery.img5.alt": "Өндірістік цех 2",
    "resources.row2.volume": "8 млн м³",
    "resources.row2.product": "құрылыс құмы",
    "resources.row3.name": "Первомайское-2 Южное",
    "resources.row3.volume": "4 млн м³",
    "resources.row3.product": "жуған құм",
    "adv.card1Text": "Бетон мен асфальт сапасын арттыру үшін шаң мен ұсақ бөлшектерді кетіру.",
    "adv.card2Title": "Заманауи жабдықтар",
    "adv.card2Text": "Sandvik және HYDROCONE сыныптау-құрастыру жабдықтары.",
    "adv.card3Title": "Сапаны бақылау",
    "adv.card3Text": "Әр партияны бірнеше сатылы тексеру, халықаралық сертификаттау.",
    "adv.card4Title": "Сенімділік",
    "adv.card4Text": "65 жылдан астам нарық тәжірибесі, тұрақты сапа, ірі тапсырыс берушілердің сенімі.",
    "resourcesTable.header1": "Атауы",
    "resourcesTable.header2": "Көлемі",
    "resourcesTable.header3": "Өнім",
    "resourcesTable.row1col1": "Котур-Булакское",
    "resourcesTable.row1col2": "10 млн м³",
    "resourcesTable.row1col3": "қиыршық тас, порфирит",
    "resourcesTable.row2col1": "Капчагайское-2",
    "resourcesTable.row2col2": "8 млн м³",
    "resourcesTable.row2col3": "құрылыс құмы",
    "resourcesTable.row3col1": "Первомайское-2 Южное",
    "resourcesTable.row3col2": "4 млн м³",
    "resourcesTable.row3col3": "жуған құм",
    "home.title": "Қиыршық тас, құм және құрылыс материалдарын өндіруші",
    "home.subtitle": "1957 жылы құрылған. Тасты өңдеу қуаты — жылына 1 000 000 тоннаға дейін.",
    "home.cta": "Бізбен байланысыңыз",
    "home.card1Title": "Сапа",
    "home.card1Text": "Өнім сапасын бақылау және ГОСТ пен халықаралық стандарттарға сәйкес сертификаттау.",
    "home.card2Title": "Жеткізілімдер",
    "home.card2Text": "Бүкіл Қазақстан бойынша құрылыс нысандарын қамтамасыз етеміз.",
    "section.aboutTitle": "Кәсіпорын туралы",
    "section.aboutText": "«АКНМ ТК» ЖШС — Қазақстандағы құрылыс саласындағы ең көне кәсіпорындардың бірі. 1957 жылы Алма-Ата қаласында инертті материалдар комбинаты ретінде құрылған. Бүгінде компания қиыршық тас, құм, қоспалар мен бетон бұйымдарын өндірумен айналысады.",
    "section.capacityTitle": "Өндірістік қуаттар",
    "section.capacityText": "Тасты өңдеудің жылдық қуаты — <b>1 000 000 тоннаға</b> дейін. Өндірістік база — 15 гектардан астам. Sandvik және HYDROCONE заманауи желілерімен жабдықталған.",
    "section.qualityTitle": "Сапаны бақылау",
    "section.qualityText": "Өнім сертификатталған және зертханалық тексеруден өтеді. Сапа Лондондағы «SANDBERG» зертханасымен расталған.",
    "section.marketTitle": "Нарықты талдау",
    "section.marketOverviewTitle": "Нарыққа шолу",
    "section.marketOverviewText": "«АКНМ ТК» ЖШС-ның Алматы және Алматы облысындағы үлесі 40%-дан асады",
    "section.marketCompetitionTitle": "Бәсекелестік орта",
    "section.marketCompetitionText1": "Негізгі бәсекелік артықшылық: М–1200+ порфиритінің бірегейлігі",
    "section.marketCompetitionText2": "Протодьяконов шкаласы бойынша 2 категория, беріктік коэффициенті 15. Тасты өңдеу технологиясы, өнімнің кең ассортименті.",
    "section.marketTrendsTitle": "Тенденциялар мен мүмкіндіктер",
    "section.marketTrendsText": "Экологиялық таза және берік құрылыс материалдарына сұраныс өсуде.<br>Өнімді Орталық Азия елдеріне экспорттау мүмкіндіктері бар.",
    "section.geographyIntro": "«АКНМ ТК» ЖШС карьерлерді игереді және Қазақстанның негізгі өңірінде жоғары сапалы өнім өндіреді, жалпы қорлары:",
    "section.geoReserve1": "«Котур Булакское» — 10 млн. м³",
    "section.geoReserve2": "«Капчагайское 2» — 8 млн. м³",
    "section.geoReserve3": "«Первомайское 2 Южный» — 4 млн. м³",
    "section.geographyConclusion": "Бұл қорлар «АКНМ ТК» компаниясына өңірде жетекші құрылыс материалдары жеткізушісі болуға мүмкіндік береді, ірі құрылыс жобалары мен Қазақстанның инфрақұрылымын қолдайды.",
    "section.projectsTitle": "Жетістіктер мен жобалар",
    "section.projectsText": "«АКНМ ТК» ЖШС бүкіл Қазақстан бойынша ірі құрылыс және инфрақұрылымдық жобаларға қатысады, жоғары сапалы құрылыс материалдарының сенімді жеткізушісі ретінде танылды.",
    "project1": "Республика сарайы",
    "project2": "Медео мұз айдыны",
    "project3": "Қазақстан қонақүйі",
    "project4": "Анкара қонақүйі",
    "project5": "Алматы әуежайы",
    "project6": "Байқоңыр космодромы",
    "project7": "Алматы метрополитені",
    "project8": "Қазақстан Темір Жолы",
    "project9": "Фарфор зауыты",
    "project10": "ТрансСтройМост",
    "project11": "KazAutoDor",
    "section.productsTitle": "Өнімдер",
    "section.productsText": "«АКНМ ТК» өнімдері құрылыс, жол және теміржол салаларында кең қолданылады, сапасы жоғары, экологиялық таза және қазіргі стандарттарға сәйкес келеді.",
    "productTable.header": "Өнім атауы",
    "productTable.item1": "Құрылысқа арналған тығыз жыныстардан қиыршық тас — ГОСТ 8267-93",
    "productTable.item2": "Теміржол балластты қабаты үшін тығыз жыныстардан қиыршық тас — ГОСТ 7392-2002",
    "productTable.item3": "Құм-құрылыс қоспалары — ГОСТ 25607-94",
    "productTable.item4": "Құрылысқа арналған құм — ГОСТ 8736-93",
    "productTable.item5": "Мәрмәрлі немесе доломитті қиыршық тас — ГОСТ 8267-93",
    "productCard.1": "Құмдалған қиыршық тас 5x20 (жуған)",
    "productCard.2": "Құрғақ қиыршық тас 5x20",
    "productCard.3": "Қиыршық тас 20x40",
    "productCard.4": "Қиыршық тас 25x60",
    "productCard.5": "Қиыршық тас 40x70",
    "productCard.6": "Қиыршық тас 70x150",
    "productCard.7": "Құм (жуған)",
    "productCard.8": "Құрғақ құм",
    "productCard.9": "Жуған құм",
    "productCard.10": "Табиғи құм",
    "productCard.11": "ПЩС (С2-0x20)",
    "productCard.12": "ПЩС (С4-0x70)",
    "productCard.13": "ПЩС (С1-0x40)",
    "productCard.14": "Қалдықтар",
    "section.resourcesTitle": "Кен орындары",
    "section.galleryTitle": "Галерея",
    "section.contactsTitle": "Байланыстар",
    "section.contactsTitle": "Байланыстар",
    "contacts.addressLabel": "Мекенжай:",
    "contacts.address": "ҚР, Алматы облысы, Талғар ауданы, Бесагаш ауылы, Чехов көшесі 9г",
    "contacts.phoneLabel": "Телефондар:",
    "contacts.phone1": "+7 (727) 387‒40‒02",
    "contacts.phone2": "+7‒775‒734‒12‒13",
    "contacts.emailLabel": "Email:",
    "contacts.email": "aknm-tk@bk.ru",
    "contacts.name": "Аты-жөні",
    "contacts.phone": "Телефон",
    "contacts.emailInput": "Email",
    "contacts.message": "Хабарлама",
    "contacts.sendButton": "Жіберу",
    "contacts.whatsappButton": "WhatsApp-та жазу"
  },
  en: {
    "section.geographyTitle": "Geography of Production",
    "nav.about": "About the Company",
    "nav.geography": "Geography of Production",
    "nav.products": "Products",
    "nav.projects": "Achievements & Key Projects", 
    "nav.contacts": "Contacts",
    "home.title": "Producer of crushed stone, sand and construction materials",
    "home.subtitle": "Founded in 1957. Stone processing capacity — up to 1,000,000 tons per year.",
    "home.cta": "Contact us",
    "section.galleryTitle": "Gallery",
    "gallery.img1.alt": "Production workshop",
    "gallery.img2.alt": "Construction equipment",
    "gallery.img3.alt": "Crushed stone",
    "gallery.img4.alt": "Construction machinery",
    "gallery.img5.alt": "Production workshop 2",
    "home.card1Title": "Quality",
    "section.resourcesTitle": "Deposits",
    "resources.header.name": "Name",
    "resources.header.volume": "Volume",
    "resources.header.product": "Products",
    "resources.row1.name": "Kotur-Bulak",
    "resources.row1.volume": "10 million m³",
    "resources.row1.product": "crushed stone, porphyrites",
    "resources.row2.name": "Kapchagai-2",
    "resources.row2.volume": "8 million m³",
    "resources.row2.product": "construction sand",
    "resources.row3.name": "Pervomayskoye-2 South",
    "resources.row3.volume": "4 million m³",
    "resources.row3.product": "washed sand",
    "section.advantagesTitle": "Technological Advantages",
    "adv.card1Title": "Crushed Stone Washing",
    "adv.card1Text": "Removal of dust and fine particles to improve concrete and asphalt quality.",
    "adv.card2Title": "Modern Equipment",
    "adv.card2Text": "Sandvik and HYDROCONE crushing and sorting lines.",
    "adv.card3Title": "Quality Control",
    "adv.card3Text": "Multi-stage inspection of each batch, international certification.",
    "adv.card4Title": "Reliability",
    "adv.card4Text": "Over 65 years in the market, stable quality, trust of major clients.",
    "section.resourcesTitle": "Deposits",
    "resourcesTable.header1": "Name",
    "resourcesTable.header2": "Volume",
    "resourcesTable.header3": "Products",
    "resourcesTable.row1col1": "Kotur-Bulak",
    "resourcesTable.row1col2": "10 million m³",
    "resourcesTable.row1col3": "crushed stone, porphyrites",
    "resourcesTable.row2col1": "Kapchagai-2",
    "resourcesTable.row2col2": "8 million m³",
    "resourcesTable.row2col3": "construction sand",
    "resourcesTable.row3col1": "Pervomayskoye-2 South",
    "resourcesTable.row3col2": "4 million m³",
    "resourcesTable.row3col3": "washed sand",
    "home.card1Text": "Quality control and certification according to GOST and international standards.",
    "home.card2Title": "Supply",
    "home.card2Text": "We supply construction sites throughout Kazakhstan.",
    "section.aboutTitle": "About the Company",
    "section.aboutText": "LLP “AKNM TK” is one of the oldest enterprises in Kazakhstan’s construction industry. Founded in 1957 as the Almaty Non-Metallic Materials Plant (AKNM). Today the company specializes in the extraction, processing, and supply of crushed stone, sand, gravel mixtures, and concrete products.",
    "section.capacityTitle": "Production Capacity",
    "section.capacityText": "Annual stone processing capacity — up to <b>1,000,000 tons</b>. The production base covers over 15 hectares. Equipped with modern Sandvik and HYDROCONE lines.",
    "section.qualityTitle": "Quality Control",
    "section.qualityText": "All products are certified and undergo regular laboratory testing. Quality confirmed by the British laboratory “SANDBERG” (London).",
    "section.marketTitle": "Market Analysis",
    "section.marketOverviewTitle": "Market Overview",
    "section.marketOverviewText": "LLP “AKNM TK” share in Almaty and Almaty region is more than 40%",
    "section.marketCompetitionTitle": "Competitive Environment",
    "section.marketCompetitionText1": "Key competitive advantage: Uniqueness of porphyrite M–1200+",
    "section.marketCompetitionText2": "Protodyakonov scale category 2, strength coefficient 15. Stone processing technology, wide product range.",
    "section.marketTrendsTitle": "Trends & Opportunities",
    "section.marketTrendsText": "Growing demand for eco-friendly and durable construction materials.<br>Opportunities for product export to Central Asian countries.",
    "section.geographyIntro": "LLP “AKNM TK” develops quarries and produces high-quality products in the main region of Kazakhstan with total reserves of:",
    "section.geoReserve1": "“Kotur Bulak” — 10 million m³",
    "section.geoReserve2": "“Kapchagai 2” — 8 million m³",
    "section.geoReserve3": "“Pervomayskoye 2 South” — 4 million m³",
    "section.geographyConclusion": "These reserves allow LLP “AKNM TK” to be a leading supplier of construction materials in the region, supporting large construction projects and Kazakhstan’s infrastructure.",
    "section.projectsTitle": "Achievements & Key Projects",
    "section.projectsText": "LLP “AKNM TK” actively participates in large construction and infrastructure projects across Kazakhstan, confirming its reputation as a reliable supplier of high-quality construction materials.",
    "project1": "Palace of the Republic",
    "project2": "Medeo Skating Rink",
    "project3": "Hotel Kazakhstan",
    "project4": "Hotel Ankara",
    "project5": "Almaty Airport",
    "project6": "Baikonur Cosmodrome",
    "project7": "Almaty Metro",
    "project8": "Kazakhstan Temir Zholy",
    "project9": "Porcelain Factories",
    "project10": "TransStroyMost",
    "project11": "KazAutoDor",
    "section.productsTitle": "Products",
    "section.productsText": "LLP “AKNM TK” products are widely used in construction, road, and railway industries, due to high quality, environmental safety, and compliance with modern standards.",
    "productTable.header": "Product Name",
    "productTable.item1": "Crushed stone from dense rocks for construction — GOST 8267-93",
    "productTable.item2": "Crushed stone from dense rocks for railway ballast — GOST 7392-2002",
    "productTable.item3": "Crushed stone and sand mixtures — GOST 25607-94",
    "productTable.item4": "Construction sand — GOST 8736-93",
    "productTable.item5": "Limestone or dolomite crushed stone — GOST 8267-93",
    "productCard.1": "Crushed stone 5x20 (washed)",
    "productCard.2": "Crushed stone 5x20 (dry)",
    "productCard.3": "Crushed stone 20x40",
    "productCard.4": "Crushed stone 25x60",
    "productCard.5": "Crushed stone 40x70",
    "productCard.6": "Crushed stone 70x150",
    "productCard.7": "Crushed sand (washed)",
    "productCard.8": "Crushed sand (dry)",
    "productCard.9": "Washed sand",
    "productCard.10": "Natural sand",
    "productCard.11": "PShS (C2-0x20)",
    "productCard.12": "PShS (C4-0x70)",
    "productCard.13": "PShS (C1-0x40)",
    "productCard.14": "Waste",
    "section.contactsTitle": "Contacts",
    "section.contactsTitle": "Contacts",
    "contacts.addressLabel": "Address:",
    "contacts.address": "RK, Almaty region, Talgar district, Besagash village, Chekhova st. 9g",
    "contacts.phoneLabel": "Phones:",
    "contacts.phone1": "+7 (727) 387‒40‒02",
    "contacts.phone2": "+7‒775‒734‒12‒13",
    "contacts.emailLabel": "Email:",
    "contacts.email": "aknm-tk@bk.ru",
    "contacts.name": "Name",
    "contacts.phone": "Phone",
    "contacts.emailInput": "Email",
    "contacts.message": "Message",
    "contacts.sendButton": "Send",
    "contacts.whatsappButton": "Write in WhatsApp"
  }
};

// === Переключение языка ===
document.addEventListener("DOMContentLoaded", () => {
  const buttons = document.querySelectorAll(".lang-switcher button");

  function setLanguage(lang) {
    const elements = document.querySelectorAll("[data-i18n]");
    elements.forEach(el => {
      const key = el.getAttribute("data-i18n");
      if (translations[lang] && translations[lang][key]) {
        el.innerHTML = translations[lang][key]; // сохраняем HTML-теги
      }
    });
    localStorage.setItem("lang", lang);
  }

  buttons.forEach(btn => {
    btn.addEventListener("click", () => {
      const lang = btn.getAttribute("data-lang");   
      setLanguage(lang);
    });
  });

});